In [36]:
import numpy as np

In [ ]:
'''
1. we can use list, tuple to create an numpy array set is not useful beacause of no indexing operation.
2. if any element is of float type it will change all elements to float.
3. default the data type of array function is int.
4. if data type is bool the 0 will be False.
5. if we give float value in arange function it will create a array of float values.
6. default data type of zeros function is float.
'''

In [86]:
#help(np.array)

In [169]:
a = np.array([1, 2, 3])
print(type(a))
print(a)
print(type(a[0]))

<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.int32'>


In [170]:
a = np.array((1,2,3))
print(type(a))
print(a)
print(type(a[0]))

<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.int32'>


In [171]:
a = np.array([1,2.0,3]) 
a

array([1., 2., 3.])

In [172]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [173]:
a = np.array([[1, 2], [3, 4]],dtype = int)
type(a)
print(type(a))
print(a)
print(type(a[0][0]))

<class 'numpy.ndarray'>
[[1 2]
 [3 4]]
<class 'numpy.int32'>


In [174]:
a = np.array([[1, 2], [3, 4]],dtype = complex)
type(a)
print(type(a))
print(a)
print(type(a[0][0]))

<class 'numpy.ndarray'>
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]
<class 'numpy.complex128'>


In [175]:
a = np.array([[1, 2], [3, 4]],dtype = float)
type(a)
print(type(a))
print(a)
print(type(a[0][0]))

<class 'numpy.ndarray'>
[[1. 2.]
 [3. 4.]]
<class 'numpy.float64'>


In [176]:
a = np.array([[1, 2], [3, 4]],dtype = str)
type(a)
print(type(a))
print(a)
print(type(a[0][0]))

<class 'numpy.ndarray'>
[['1' '2']
 ['3' '4']]
<class 'numpy.str_'>


In [177]:
a = np.array([[0, 0], [3, 4]],dtype = bool)
type(a)
print(type(a))
print(a)
print(type(a[0][0]))

<class 'numpy.ndarray'>
[[False False]
 [ True  True]]
<class 'numpy.bool_'>


### arange

In [178]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [179]:
b = np.arange(3.0)
b

array([0., 1., 2.])

In [180]:
print(np.arange(1,10))

[1 2 3 4 5 6 7 8 9]


In [181]:
print(np.arange(1,10,2))

[1 3 5 7 9]


In [182]:
print(np.arange(1,10, dtype = float))

[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [ ]:
print(np.arange(1,10,2, dtype = float))

### zeros

In [87]:
#help(np.zeros)

In [3]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [4]:
print(np.zeros(5, dtype = int))

[0 0 0 0 0]


In [5]:
print(np.zeros((3,3), dtype = int))

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [6]:
print(np.zeros([3,3], dtype = int))

[[0 0 0]
 [0 0 0]
 [0 0 0]]


### ones

In [7]:
print(np.ones(5))

[1. 1. 1. 1. 1.]


In [9]:
print(np.ones(5,dtype = int))

[1 1 1 1 1]


In [10]:
print(np.ones((3,3),dtype = int))

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [11]:
print(np.ones([3,3],dtype = int))

[[1 1 1]
 [1 1 1]
 [1 1 1]]


### linspace

In [88]:
#help(np.linspace)

In [15]:
print(np.linspace(1,6))

[1.         1.10204082 1.20408163 1.30612245 1.40816327 1.51020408
 1.6122449  1.71428571 1.81632653 1.91836735 2.02040816 2.12244898
 2.2244898  2.32653061 2.42857143 2.53061224 2.63265306 2.73469388
 2.83673469 2.93877551 3.04081633 3.14285714 3.24489796 3.34693878
 3.44897959 3.55102041 3.65306122 3.75510204 3.85714286 3.95918367
 4.06122449 4.16326531 4.26530612 4.36734694 4.46938776 4.57142857
 4.67346939 4.7755102  4.87755102 4.97959184 5.08163265 5.18367347
 5.28571429 5.3877551  5.48979592 5.59183673 5.69387755 5.79591837
 5.89795918 6.        ]


In [16]:
print(np.linspace(1,6,num = 5))

[1.   2.25 3.5  4.75 6.  ]


In [17]:
print(np.linspace(1,6,num=5,endpoint = True))

[1.   2.25 3.5  4.75 6.  ]


In [18]:
print(np.linspace(1,6,num=5,endpoint = False))

[1. 2. 3. 4. 5.]


In [20]:
print(np.linspace(1,6,num=5,retstep = False))

[1.   2.25 3.5  4.75 6.  ]


In [21]:
print(np.linspace(1,6,num=5,retstep = True))

(array([1.  , 2.25, 3.5 , 4.75, 6.  ]), 1.25)


In [22]:
print(np.linspace(1,6,num=5,dtype = int))

[1 2 3 4 6]


### Eye

In [89]:
#help(np.eye)

In [24]:
print(np.eye(2)) # k = 0

[[1. 0.]
 [0. 1.]]


In [26]:
print(np.eye(2,dtype = int)) # k = 0

[[1 0]
 [0 1]]


In [27]:
print(np.eye(2,M= 3,dtype = int)) # k = 0

[[1 0 0]
 [0 1 0]]


In [42]:
print(np.eye(3,k = 0,dtype = int))

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [44]:
print(np.eye(3,k = 1,dtype = int))

[[0 1 0]
 [0 0 1]
 [0 0 0]]


In [46]:
print(np.eye(3,k = 2,dtype = int))

[[0 0 1]
 [0 0 0]
 [0 0 0]]


In [47]:
print(np.eye(3,k = -1,dtype = int))

[[0 0 0]
 [1 0 0]
 [0 1 0]]


In [48]:
print(np.eye(3,k = -2,dtype = int))

[[0 0 0]
 [0 0 0]
 [1 0 0]]


### identity

In [90]:
#help(np.identity)

In [50]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [51]:
print(np.identity(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [53]:
print(np.identity(3,dtype = int))

[[1 0 0]
 [0 1 0]
 [0 0 1]]


### random

In [91]:
#help(np.random)

In [92]:
#help(np.random.rand)

In [56]:
print(np.random.rand(5))

[3.36906316e-01 9.30567132e-01 3.44578359e-01 8.46798285e-01
 8.68413497e-04]


In [57]:
print(np.random.rand(3,3))

[[0.31456095 0.61556387 0.68014012]
 [0.42605131 0.25301512 0.60730305]
 [0.61222436 0.77105186 0.46649678]]


In [93]:
#help(np.random.randn)

In [60]:
np.random.randn(5)

array([-1.3380542 , -0.7543217 , -0.38740404,  1.07361433,  0.10981146])

In [61]:
np.random.randn(3,3)

array([[-0.49304093, -1.59591613,  0.15527312],
       [-0.23124077, -0.55144486,  0.78934117],
       [ 0.12163117, -0.4782099 , -2.11913982]])

In [62]:
np.random.randn()

0.7737619571204299

In [94]:
#help(np.random.ranf)

In [66]:
np.random.ranf()

0.06267031735477546

In [67]:
np.random.ranf(5)

array([0.42656884, 0.11254775, 0.01083302, 0.77440808, 0.38061242])

In [70]:
np.random.ranf((3,3))

array([[0.12792613, 0.39627459, 0.64339448],
       [0.65532417, 0.6317383 , 0.84885885],
       [0.38946954, 0.46480536, 0.54703434]])

In [95]:
#help(np.random.randint)

In [84]:
np.random.randint(5)

4

In [86]:
np.random.randint(5,size = 10)

array([0, 0, 4, 4, 1, 4, 4, 3, 3, 1])

In [87]:
np.random.randint(5,size = (3,3))

array([[3, 4, 2],
       [2, 3, 2],
       [0, 1, 2]])

# attributes

In [98]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [99]:
a.ndim

2

In [100]:
a.shape

(2, 3)

In [106]:
a.size

6

In [109]:
a.dtype

dtype('int32')

In [110]:
a.itemsize

4

### indexing

In [111]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [112]:
a[0]

1

In [113]:
a[1]

2

In [114]:
a[-1]

6

In [115]:
a[-2]

5

In [129]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [130]:
a[0]

array([1, 2, 3])

In [131]:
a[1]

array([4, 5, 6])

In [132]:
a[2]

array([7, 8, 9])

In [133]:
a[0][0]

1

In [134]:
a[0][1]

2

In [135]:
a[0][2]

3

In [136]:
a[1][0]

4

In [137]:
a[1][1]

5

In [138]:
a[1][2]

6

In [139]:
a[2][0]

7

In [140]:
a[2][1]

8

In [141]:
a[2][2]

9

In [144]:
a = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [146]:
a[0][1][1] # i = 0 for first 2 d array 

5

In [148]:
a[1][2][1] # i = 1 for second array

17

In [2]:
'''
if I want to get different values from array then [[r,r,.....][c,c,.....] ] 
'''
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
b[[0,1,2],[0,1,2]]

array([1, 5, 9])

In [6]:
a = np.array([1,2,3,4,7,8,5,9,6])
a

array([1, 2, 3, 4, 7, 8, 5, 9, 6])

In [7]:
a[[1,2,1,2,3,5]]

array([2, 3, 2, 3, 4, 8])

In [8]:
'''
if i want some specific items fullfilling a condition then
'''
a[a>5]

array([7, 8, 9, 6])

### slicing 

In [149]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [164]:
a[1:,1:]

array([[5, 6],
       [8, 9]])

In [165]:
a[2][1:]

array([8, 9])

In [163]:
a[0][1:]

array([2, 3])

In [166]:
a[0:,2:]

array([[3],
       [6],
       [9]])

### arithmetic operations

In [9]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [10]:
a+2

array([3, 4, 5, 6, 7])

In [11]:
a*3

array([ 3,  6,  9, 12, 15])

In [12]:
a/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [13]:
a-1

array([0, 1, 2, 3, 4])

In [14]:
a**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [15]:
a%2

array([1, 0, 1, 0, 1], dtype=int32)

In [16]:
a = np.array([[1,2,3],[2,4,5]])
a

array([[1, 2, 3],
       [2, 4, 5]])

In [17]:
a+2

array([[3, 4, 5],
       [4, 6, 7]])

In [18]:
a*2

array([[ 2,  4,  6],
       [ 4,  8, 10]])

In [19]:
a/2

array([[0.5, 1. , 1.5],
       [1. , 2. , 2.5]])

In [20]:
a-1

array([[0, 1, 2],
       [1, 3, 4]])

In [21]:
a**2

array([[ 1,  4,  9],
       [ 4, 16, 25]], dtype=int32)

In [22]:
a%2

array([[1, 0, 1],
       [0, 0, 1]], dtype=int32)

In [23]:
a = np.arange(1,5)
a

array([1, 2, 3, 4])

In [27]:
b = np.arange(1,9,2)
b

array([1, 3, 5, 7])

In [28]:
a+b

array([ 2,  5,  8, 11])

In [37]:
np.add(a,b)

array([ 2,  5,  8, 11])

In [29]:
b-a

array([0, 1, 2, 3])

In [38]:
np.subtract(b,a)

array([0, 1, 2, 3])

In [30]:
a*b

array([ 1,  6, 15, 28])

In [39]:
np.multiply(a,b)

array([ 1,  6, 15, 28])

In [33]:
b//a

array([1, 1, 1, 1], dtype=int32)

In [34]:
a/b

array([1.        , 0.66666667, 0.6       , 0.57142857])

In [40]:
np.divide(a,b)

array([1.        , 0.66666667, 0.6       , 0.57142857])

In [42]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
b = np.array([[3,4,7],[2,5,8],[1,6,9]])
b

array([[3, 4, 7],
       [2, 5, 8],
       [1, 6, 9]])

In [44]:
a+b

array([[ 4,  6, 10],
       [ 6, 10, 14],
       [ 8, 14, 18]])

In [46]:
np.add(a,b)

array([[ 4,  6, 10],
       [ 6, 10, 14],
       [ 8, 14, 18]])

In [47]:
np.subtract(b,a)

array([[ 2,  2,  4],
       [-2,  0,  2],
       [-6, -2,  0]])

In [48]:
np.divide(b,a)

array([[3.        , 2.        , 2.33333333],
       [0.5       , 1.        , 1.33333333],
       [0.14285714, 0.75      , 1.        ]])

In [49]:
np.multiply(b,a)

array([[ 3,  8, 21],
       [ 8, 25, 48],
       [ 7, 48, 81]])

In [50]:
np.dot(a,b)

array([[ 10,  32,  50],
       [ 28,  77, 122],
       [ 46, 122, 194]])

In [51]:
np.mod(a,b)

array([[1, 2, 3],
       [0, 0, 6],
       [0, 2, 0]], dtype=int32)

In [54]:
np.power(a,b)

array([[        1,        16,      2187],
       [       16,      3125,   1679616],
       [        7,    262144, 387420489]], dtype=int32)

In [55]:
np.power(a,2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)

In [58]:
np.sum(a,axis = 0) # axis = 0 for columns

array([12, 15, 18])

In [60]:
np.sum(a,axis = 1)

array([ 6, 15, 24])

### broadcasting

In [40]:
a = np.array([10,20,30])
print(a,a.shape)

[10 20 30] (3,)


In [41]:
b = np.array([1,2,3,4])
print(b,b.shape)

[1 2 3 4] (4,)


In [42]:
a+b

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [ ]:
'''
1. size of each dimension should be same
2. size of one of dimension should be 1.


'''

In [43]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
b = np.array([10,20,30])
b

array([10, 20, 30])

In [45]:
c = np.array([10,20])
c

array([10, 20])

In [46]:
a+b

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39]])

In [47]:
a+c

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

In [50]:
a = np.array([[1],[2],[3]])
b = np.array([10,20,30])

In [51]:
a+b

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

In [52]:
a = np.array([[11,25,16],[20,11,15]])
b = np.array([[29,35],[29,30],[19,32]])

In [53]:
a+b

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [54]:
'''
1. shape
2. dimension
3. size of dimension should be same
'''

'\n1. shape\n2. dimension\n3. size of dimension should be same\n'

### array manipulation

##### reshaping and resizing

In [67]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(a)
print(a.shape)

[1 2 3 4 5 6 7 8 9]
(9,)


In [72]:
b= np.reshape(a,(3,3), order = "C") # C = Row wise
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
c = np.reshape(a,(3,3),order = "F") # F = Column wise
c

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

or

In [71]:
# a.shape = (3,3)
# a

In [82]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
np.resize(a,(2,4))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [84]:
a.resize((3,3))


In [85]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### flatten 

In [97]:
a = np.array([[[1,2,3],[4,5,6]],[[6,7,8],[9,10,11]]])
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [99]:
a.flatten() # order = C

array([ 1,  2,  3,  4,  5,  6,  6,  7,  8,  9, 10, 11])

In [103]:
a.flatten(order = "F")

array([ 1,  6,  4,  9,  2,  7,  5, 10,  3,  8,  6, 11])

#### ravel

In [104]:
np.ravel(a)

array([ 1,  2,  3,  4,  5,  6,  6,  7,  8,  9, 10, 11])

In [105]:
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [106]:
np.ravel(a,"F")

array([ 1,  6,  4,  9,  2,  7,  5, 10,  3,  8,  6, 11])

In [109]:
a.ravel()

array([ 1,  2,  3,  4,  5,  6,  6,  7,  8,  9, 10, 11])

In [110]:
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

#### transpose

In [121]:
arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [123]:
np.transpose(arr,(0,1))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [124]:
np.transpose(arr,(1,0))

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [114]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [136]:
arr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [125]:
arr1 = np.arange(1,25).reshape(2,3,4)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [129]:
np.transpose(arr1)

array([[[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]],

       [[ 4, 16],
        [ 8, 20],
        [12, 24]]])

In [130]:
np.transpose(arr1,axes = (0,1,2))

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [131]:
np.transpose(arr1,axes = (0,2,1))

array([[[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]],

       [[13, 17, 21],
        [14, 18, 22],
        [15, 19, 23],
        [16, 20, 24]]])

In [132]:
np.transpose(arr1,axes = (2,1,0))

array([[[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]],

       [[ 4, 16],
        [ 8, 20],
        [12, 24]]])

In [133]:
np.transpose(arr1,axes = (2,0,1))

array([[[ 1,  5,  9],
        [13, 17, 21]],

       [[ 2,  6, 10],
        [14, 18, 22]],

       [[ 3,  7, 11],
        [15, 19, 23]],

       [[ 4,  8, 12],
        [16, 20, 24]]])

In [135]:
arr1.T

array([[[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]],

       [[ 4, 16],
        [ 8, 20],
        [12, 24]]])

In [118]:
a = np.arange(1,10)
np.transpose(a)  # no change

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#### swap axes

In [137]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [138]:
np.swapaxes(arr,0,1)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [142]:
np.swapaxes(arr,1,0)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [143]:
arr1

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [147]:
np.swapaxes(arr1,0,1) # 0 for matrix 1 for row 2 for column

array([[[ 1,  2,  3,  4],
        [13, 14, 15, 16]],

       [[ 5,  6,  7,  8],
        [17, 18, 19, 20]],

       [[ 9, 10, 11, 12],
        [21, 22, 23, 24]]])

In [148]:
np.swapaxes(arr1,0,2)

array([[[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]],

       [[ 4, 16],
        [ 8, 20],
        [12, 24]]])

In [149]:
np.swapaxes(arr1,1,2)

array([[[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]],

       [[13, 17, 21],
        [14, 18, 22],
        [15, 19, 23],
        [16, 20, 24]]])

In [150]:
arr1.shape

(2, 3, 4)

In [151]:
np.swapaxes(arr1,1,2).shape

(2, 4, 3)

In [152]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [153]:
arr.swapaxes(0,1)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

#### concatenate

In [171]:
a = np.arange(1,5)

In [172]:
b = np.arange(1,7)

In [173]:
np.concatenate((a,b))

array([1, 2, 3, 4, 1, 2, 3, 4, 5, 6])

In [174]:
np.concatenate((a,b),out = c)

array([1., 2., 3., 4., 1., 2., 3., 4., 5., 6.])

In [175]:
c = np.array([0])

In [176]:
np.concatenate((a,b),out = c)

ValueError: Output array is the wrong shape

In [182]:
c = np.zeros(10,dtype = int)
c

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [183]:
np.concatenate((a,b), out = c)

array([1, 2, 3, 4, 1, 2, 3, 4, 5, 6])

In [184]:
c

array([1, 2, 3, 4, 1, 2, 3, 4, 5, 6])

In [185]:
a = np.array([[1,2],[10,29]])
a

array([[ 1,  2],
       [10, 29]])

In [196]:
b = np.array([[1,3]])
b

array([[1, 3]])

In [197]:
np.concatenate((a,b))

array([[ 1,  2],
       [10, 29],
       [ 1,  3]])

In [198]:
np.concatenate((a,b),axis = 1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [207]:
b.T

array([[1],
       [3]])

In [206]:
np.concatenate((a,b.T),axis = 1)

array([[ 1,  2,  1],
       [10, 29,  3]])

#### vstack 

In [213]:
a = np.arange(1,5)
b = np.arange(2,10,2)
c = np.arange(1,6)

In [212]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [2, 4, 6, 8]])

In [214]:
np.vstack((a,c))

ValueError: all the input array dimensions except for the concatenation axis must match exactly

#### hstack 

In [218]:
a

array([1, 2, 3, 4])

In [219]:
b

array([2, 4, 6, 8])

In [220]:
c

array([1, 2, 3, 4, 5])

In [217]:
np.hstack((a,c))

array([1, 2, 3, 4, 1, 2, 3, 4, 5])

#### split

In [261]:
arr = np.arange(1,13).reshape(4,3)
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [262]:
np.split(arr,2, axis = 1)

ValueError: array split does not result in an equal division

In [263]:
np.split(arr,2,axis = 0)

[array([[1, 2, 3],
        [4, 5, 6]]), array([[ 7,  8,  9],
        [10, 11, 12]])]

In [235]:
np.split(arr,4)

[array([[1, 2, 3]]),
 array([[4, 5, 6]]),
 array([[7, 8, 9]]),
 array([[10, 11, 12]])]

In [224]:
np.split(arr,5)

ValueError: array split does not result in an equal division

#### vsplit

In [236]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [238]:
np.vsplit(arr,2)

[array([[1, 2, 3],
        [4, 5, 6]]), array([[ 7,  8,  9],
        [10, 11, 12]])]

In [240]:
np.split(arr,4)

[array([[1, 2, 3]]),
 array([[4, 5, 6]]),
 array([[7, 8, 9]]),
 array([[10, 11, 12]])]

In [241]:
np.split(arr,3)

ValueError: array split does not result in an equal division

#### hsplit

In [2]:
arr = np.arange(1,25).reshape(2,12)
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [252]:
np.hsplit(arr,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]), array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]), array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [253]:
np.hsplit(arr,4)

[array([[ 1,  2,  3],
        [13, 14, 15]]), array([[ 4,  5,  6],
        [16, 17, 18]]), array([[ 7,  8,  9],
        [19, 20, 21]]), array([[10, 11, 12],
        [22, 23, 24]])]

In [255]:
np.hsplit(arr,6)

[array([[ 1,  2],
        [13, 14]]), array([[ 3,  4],
        [15, 16]]), array([[ 5,  6],
        [17, 18]]), array([[ 7,  8],
        [19, 20]]), array([[ 9, 10],
        [21, 22]]), array([[11, 12],
        [23, 24]])]

In [3]:
np.hsplit(arr,8)

ValueError: array split does not result in an equal division

#### insert

1d array

In [4]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
np.insert(a,1,50)

array([ 1, 50,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
np.insert(a,1,50.5)

array([ 1, 50,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
np.insert(a,(1,3),50.5)

array([ 1, 50,  2,  3, 50,  4,  5,  6,  7,  8,  9, 10])

2d array

In [8]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [9]:
np.insert(a,1,23)

array([ 1, 23,  2,  3,  4])

In [10]:
np.insert(a,1,23,axis = 0)

array([[ 1,  2],
       [23, 23],
       [ 3,  4]])

In [11]:
np.insert(a,1,23,axis = 1)

array([[ 1, 23,  2],
       [ 3, 23,  4]])

In [12]:
np.insert(a,1,[23,25],axis = 1)

array([[ 1, 23,  2],
       [ 3, 25,  4]])

In [14]:
np.insert(a,0,[23,25],axis = 0)

array([[23, 25],
       [ 1,  2],
       [ 3,  4]])

In [15]:
np.insert(a,0,[23,25,21],axis = 0)

ValueError: could not broadcast input array from shape (1,3) into shape (1,2)

#### append

In [16]:
help(np.append)

Help on function append in module numpy:

append(arr, values, axis=None)
    Append values to the end of an array.
    
    Parameters
    ----------
    arr : array_like
        Values are appended to a copy of this array.
    values : array_like
        These values are appended to a copy of `arr`.  It must be of the
        correct shape (the same shape as `arr`, excluding `axis`).  If
        `axis` is not specified, `values` can be any shape and will be
        flattened before use.
    axis : int, optional
        The axis along which `values` are appended.  If `axis` is not
        given, both `arr` and `values` are flattened before use.
    
    Returns
    -------
    append : ndarray
        A copy of `arr` with `values` appended to `axis`.  Note that
        `append` does not occur in-place: a new array is allocated and
        filled.  If `axis` is None, `out` is a flattened array.
    
    See Also
    --------
    insert : Insert elements into an array.
    delete : Delet

In [18]:
np.append([1, 2, 3], [[4, 5, 6], [7, 8, 9]])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.append([[1, 2, 3], [4, 5, 6]], [[7, 8, 9]],axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
np.append([[1, 2, 3], [4, 5, 6]], [[7, 8, 9]],axis = 1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly

#### delete

1d array

In [24]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
np.delete(a,4)

array([ 1,  2,  3,  4,  6,  7,  8,  9, 10])

In [26]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

2d array 

In [29]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [31]:
np.delete(a,2)

array([1, 2, 4])

In [32]:
np.delete(a,1,axis = 0)

array([[1, 2]])

In [33]:
np.delete(a,0,axis = 0)

array([[3, 4]])

In [34]:
np.delete(a,1,axis = 1)

array([[1],
       [3]])

In [35]:
np.delete(a,0,axis = 1)

array([[2],
       [4]])

## matrix in numpy

In [55]:
n = np.array([[20,30],[40,60]])
m = np.array([[15,2],[3,16]])


In [56]:
np.multiply(n,m)

array([[300,  60],
       [120, 960]])

In [57]:
np.dot(n,m)

array([[ 390,  520],
       [ 780, 1040]])

In [58]:
n.transpose()

array([[20, 40],
       [30, 60]])

In [66]:
a = np.matrix("1 2; 3,4")
print(a)

[[1 2]
 [3 4]]


In [70]:
a = np.matrix([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [71]:
a

matrix([[1, 2],
        [3, 4]])

In [72]:
b = np.matrix("1 2; 3,4")
print(b)

[[1 2]
 [3 4]]


In [74]:
a*b # no need to use .dot method

matrix([[ 7, 10],
        [15, 22]])

In [75]:
a.T

matrix([[1, 3],
        [2, 4]])

## linear algebra

### inverse 

In [77]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [91]:
b = np.linalg.inv(a)
b

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [90]:
np.allclose(np.dot(a,b),np.eye(2,dtype = int)) # allclose checking whether dot product and identity matrix are equall or not

True

### matrix power

In [92]:
a

array([[1, 2],
       [3, 4]])

In [93]:
np.linalg.matrix_power(a,2)

array([[ 7, 10],
       [15, 22]])

In [94]:
np.dot(a,a)

array([[ 7, 10],
       [15, 22]])

In [95]:
np.linalg.matrix_power(a,0)

array([[1, 0],
       [0, 1]])

In [97]:
np.linalg.matrix_power(a,-1)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [100]:
np.linalg.matrix_power([[1,2,3],[2,1,5]],2)

LinAlgError: Last 2 dimensions of the array must be square

### linear eqn

In [ ]:
'''
x+5y = 9
9x+2y = 38


[[1,5],
[9,2]]


[9,38]
'''

In [101]:
xy = np.array([[1,5],[9,2]])
print(xy)
eq = np.array([9,38])
print(eq)

[[1 5]
 [9 2]]
[ 9 38]


In [102]:
np.linalg.solve(xy,eq)

array([4., 1.])

In [ ]:
'''
6x+5y+2z = 22
2x+3y+4z = 20
x+y+z = 6

'''

In [103]:
xyz = np.array([[6,5,2],[2,3,4],[1,1,1]])
xyz

array([[6, 5, 2],
       [2, 3, 4],
       [1, 1, 1]])

In [105]:
eq1 = np.array([22,20,6])

In [106]:
np.linalg.solve(xyz,eq1)

array([1., 2., 3.])

### determinant 

In [107]:
a

array([[1, 2],
       [3, 4]])

In [115]:
np.linalg.det(a)

-2.0000000000000004

In [109]:
round(np.linalg.det(a))

-2.0

In [110]:
xyz

array([[6, 5, 2],
       [2, 3, 4],
       [1, 1, 1]])

In [116]:
np.linalg.det(xyz)

2.0

In [113]:
v = np.arange(1,10).reshape(3,3)
v

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [117]:
np.linalg.det(v)

-9.51619735392994e-16

In [118]:
round(np.linalg.det(v))

-0.0